-- Pizza Sales Analysis using SQL
-- This project explores pizza sales data to understand revenue,
-- popular items, customer preferences, and sales trends.

--------------------------------------------------
-- BASIC ORDER & SALES OVERVIEW
--------------------------------------------------

-- Checking total number of orders placed
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM orders;

-- Calculating total revenue generated from all pizza sales
-- Price is taken from the pizzas table, quantity from order_details
SELECT ROUND(SUM(od.quantity * p.price), 2) AS total_revenue
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id;

--------------------------------------------------
-- PRODUCT & SIZE ANALYSIS
--------------------------------------------------

-- Identifying the most expensive pizza available
SELECT pt.name AS pizza_name, p.price
FROM pizzas p
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
ORDER BY p.price DESC
LIMIT 1;

-- Finding which pizza size is ordered the most
SELECT p.size, SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
GROUP BY p.size
ORDER BY total_quantity DESC;

-- Top 5 most ordered pizza types
SELECT pt.name AS pizza_name, SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY total_quantity DESC
LIMIT 5;

--------------------------------------------------
-- CATEGORY-LEVEL INSIGHTS
--------------------------------------------------

-- Total quantity of pizzas sold in each category
SELECT pt.category, SUM(od.quantity) AS total_quantity
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY total_quantity DESC;

-- Revenue generated by each pizza category
SELECT pt.category,
       ROUND(SUM(od.quantity * p.price), 2) AS category_revenue
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category
ORDER BY category_revenue DESC;

-- Percentage contribution of each category to total revenue
SELECT pt.category,
       ROUND(SUM(od.quantity * p.price) * 100 /
       (SELECT SUM(od.quantity * p.price)
        FROM order_details od
        JOIN pizzas p ON od.pizza_id = p.pizza_id), 2) AS revenue_percentage
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.category;

--------------------------------------------------
-- TIME-BASED ANALYSIS
--------------------------------------------------

-- Distribution of orders by hour of the day
SELECT HOUR(order_time) AS order_hour,
       COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_hour
ORDER BY order_hour;

-- Analyzing daily order volume
SELECT o.order_date,
       COUNT(DISTINCT o.order_id) AS total_orders
FROM orders o
GROUP BY o.order_date
ORDER BY o.order_date;

-- Calculating average number of pizzas ordered per day
SELECT ROUND(AVG(daily_quantity), 2) AS avg_pizzas_per_day
FROM (
    SELECT o.order_date,
           SUM(od.quantity) AS daily_quantity
    FROM orders o
    JOIN order_details od
    ON o.order_id = od.order_id
    GROUP BY o.order_date
) AS daily_orders;

--------------------------------------------------
-- REVENUE TRENDS & ADVANCED INSIGHTS
--------------------------------------------------

-- Top 3 pizza types based on revenue
SELECT pt.name AS pizza_name,
       ROUND(SUM(od.quantity * p.price), 2) AS revenue
FROM order_details od
JOIN pizzas p
ON od.pizza_id = p.pizza_id
JOIN pizza_types pt
ON p.pizza_type_id = pt.pizza_type_id
GROUP BY pt.name
ORDER BY revenue DESC
LIMIT 3;

-- Tracking cumulative revenue over time
-- Helps understand how revenue builds day by day
SELECT o.order_date,
       ROUND(SUM(od.quantity * p.price), 2) AS daily_revenue,
       ROUND(SUM(SUM(od.quantity * p.price))
       OVER (ORDER BY o.order_date), 2) AS cumulative_revenue
FROM orders o
JOIN order_details od
ON o.order_id = od.order_id
JOIN pizzas p
ON od.pizza_id = p.pizza_id
GROUP BY o.order_date
ORDER BY o.order_date;

-- Top 3 pizzas by revenue within each category
SELECT category, pizza_name, revenue
FROM (
    SELECT pt.category,
           pt.name AS pizza_name,
           ROUND(SUM(od.quantity * p.price), 2) AS revenue,
           RANK() OVER (PARTITION BY pt.category
                        ORDER BY SUM(od.quantity * p.price) DESC) AS rank_in_category
    FROM order_details od
    JOIN pizzas p
    ON od.pizza_id = p.pizza_id
    JOIN pizza_types pt
    ON p.pizza_type_id = pt.pizza_type_id
    GROUP BY pt.category, pt.name
) ranked_pizzas
WHERE rank_in_category <= 3;
